apiVersion: apps/v1
kind: Deployment
metadata:
  name: brain-task-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: brain-task-app
  template:
    metadata:
      labels:
        app: brain-task-app
    spec:
      imagePullSecrets:
      - name: ecr-secret
      containers:
      - name: brain-task-app
        image: 045998146012.dkr.ecr.us-east-1.amazonaws.com/brain-tasks-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000


